# Documentation: http://docs.travis-ci.com/user/languages/julia/
language: julia
os:
  - linux
  - osx
julia:
  - release
  - nightly
notifications:
  email: false
git:
  depth: 99999999

## uncomment the following lines to allow failures on nightly julia
## (tests will run but not make your overall status red)
#matrix:
  allow_failures:
  - julia: nightly
# uncomment the following lines to override the default test script
#script:
#  - if [[ -a .git/shallow ]]; then git fetch --unshallow; fi
#  - julia -e 'Pkg.clone(pwd()); Pkg.build("FastFieldSolversHelper"); Pkg.test("FastFieldSolversHelper"; coverage=true)'

after_success:
  - julia -e 'cd(Pkg.dir("FastHenryHelper")); Pkg.add("Coverage"); using Coverage; Coveralls.submit(process_folder())'
