site_name:        FastHenryHelper.jl
repo_url:         https://github.com/cstook/FastHenryHelper.jl
site_description: Use Julia to create FastHenry input files.
site_author:      Chris Stook

theme: readthedocs

extra_css:
  - assets/Documenter.css

markdown_extensions:
  - extra
  - tables
  - fenced_code

extra_javascript:
  - https://cdn.mathjax.org/mathjax/latest/MathJax.js?config=TeX-AMS_HTML
  - assets/mathjaxhelper.js

docs_dir: 'build'

pages:
- Home: index.md
- Installation: install.md
- Examples: examples.md
- Public API: public.md
#- Internal API: internal.md